### PR TITLE
remove extra padding from cards

### LINKED ISSUE #126: [Feature panel] Reduce padding around record/observation cards

### PR DESCRIPTION
**Pull request by dhvogel**
closes #126

### CODE REVIEW

**Comment by dhvogel** [comment]
also closes #118

**Comment by gino-m** [comment]
@dhvogel Seems there are some conflicts now.. would you mind merging with `master` and pushing again?

**Comment by dhvogel** [comment]
@gino-m There is one change here that I would like your opinion on: I changed the default font to "Google Sans". It looks like the font used in the mocks (and the one that google uses). Let me know if you think this is a good change or not. If not we can take it out.

**Comment by dhvogel** [comment]
Otherwise this is merge-able

**Comment by gino-m** [comment]
> @gino-m There is one change here that I would like your opinion on: I changed the default font to "Google Sans". It looks like the font used in the mocks (and the one that google uses). Let me know if you think this is a good change or not. If not we can take it out.

Google Sans is generally used for larger heading and titles in Google-branded products, so it wouldn't really be appropriate to use it here. Please feel free to change it in a follow up PR if you don't want to revert it in this one. Thanks for the fixes!

**Comment by dhvogel** [comment]
reverted the font change, needs another lgtm

**Pull request merged**
