### PR TITLE
Fix canImport permission

### PR DESCRIPTION
**Pull request by rfontanarosa**
@gino-m PTAL?

 (survey organizer was not able to import geojson)

### CODE REVIEW

**Review by nwkotto — APPROVED** [review]
The change itself looks pretty straightforward, but where are these roles defined? Where did you see where to change this to? Just asking so I can reference that.

**Comment by rfontanarosa** [comment]
> The change itself looks pretty straightforward, but where are these roles defined? Where did you see where to change this to? Just asking so I can reference that.

I hadn't noticed this before, but at survey creation the assigned role is "OWNER." However, if I understand correctly, the "OWNER" role will be deprecated in favor of "SURVEY_ORGANIZER."

Additionally, the "DATA_COLLECTOR" role cannot edit surveys. This means they won't have access to the "IMPORT SITES" button in the interface.

**Comment by nwkotto** [comment]
That makes sense to me. But how did you know that 'SURVEY_ORGANIZER' was the correct string to use for that role? Is that defined in Firebase somwhere?

**Comment by rfontanarosa** [comment]
nope, it's not defined in firebase, it was defined by the applications (web/android/functions), but soon the will be defined by proto model (and so centralised)

**Pull request merged**
