### PR TITLE
[Layer Creation Dialog] Required selector doesn't work

### LINKED ISSUE #774: [Layer Creation Dialog] Required selector doesn't work
**Describe the bug**
When toggling "Required" for a question, the question editor closes and the state of the toggle is not updated.

**To Reproduce**
1. Add layer
2. Add a question, filling out details. Type text + Choose one.
3. Toggle  **Required**

**Expected behavior**
Toggle functions correctly and the field is marked as required.

**Screenshots**

https://user-images.githubusercontent.com/11237600/123974759-df4cd200-d98a-11eb-9677-c4c7b41a9802.mov

### PR DESCRIPTION
**Pull request by DakshSaini**
Closes #774 

On tab key press the collapse will occur. The click collapse is handled by HostListener.

### CODE REVIEW

**Comment by gino-m** [comment]
@DakshSaini The form doesn't collapse as soon as hit you `Tab`?

**Comment by DakshSaini** [comment]
> @DakshSaini The form doesn't collapse as soon as hit you `Tab`?

@gino-m Collapse occurs when tab key is pressed on focused required slide toggle.
Screen recording showcasing this -

https://user-images.githubusercontent.com/45903885/124185291-65971000-da80-11eb-8233-0c46df2541f8.mov

**Review by DaoyuT — APPROVED** [review]
LGTM

**Comment by DaoyuT** [comment]
> @DakshSaini The form doesn't collapse as soon as hit you `Tab`?

It doesn't collapse only because you hit `Tab`, but it collapse if you `Tab` out of the question.
Clicking out of the question also collapse because HostListener was set up.

Thanks for fixing this, Daksh.

**Pull request merged**
