### PR TITLE
[Layers list] Add overflow menu with "Download CSV"

### LINKED ISSUE #268: [Layers list] Add overflow menu with "Download CSV"
Forked from #188.

### PR DESCRIPTION
**Pull request by parulraheja98**
Screen Shot 2020-09-07 at 5 29 14 PM

Closes #268

### CODE REVIEW

**Review by gino-m — APPROVED** [review]
LGTM. Thanks for adding the link!

**Review by gino-m — CHANGES_REQUESTED** [review]
Looks like tests are failing with:
```
ERROR in src/app/components/layer-list-item/layer-list-item.component.ts:22:36 - error TS2307: Cannot find module '../../../../.backend-config.json'.

22 import { cloudFunctionsHost } from '../../../../.backend-config.json';
                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

To fix this, we would need to create a fake .backend-config.json file in the test environment. Could you kindly look into this?

**Comment by parulraheja98** [comment]
Done @gino-m

**Review by gino-m — APPROVED** [review]
That's exactly what I had in mind. Thanks for the quick update!

**Pull request merged**
