### PR TITLE
[Layer dialog] No fields should be required in question if nothing is filled in

### LINKED ISSUE #494: [Layer dialog] Can't save new layer on new project
To repro:

1. Navigate to /p/:new.
2. Enter project title, hit Enter.
3. Click "Add layer"
4. Enter layer title, hit Enter.
5. Click save.

Expected result:
Layer is saved and dialog is closed.

Actual result:
No response from UI, error shown in console log:
```
firestore.googleapis.com/google.firestore.v1.Firestore/Write/channel?database=projects%2F<project>%2Fdatabases%2F(default)&gsessionid=scYmTAmedq2aEDfXYzmxaBAOZZNTjCgs&VER=8&RID=rpc&SID=MgHfWJLtJw8PnKZTMw0PXA&CI=0&AID=0&TYPE=xmlhttp&zx=g6xui2nxvtxg&t=1:1 
```

### LINKED ISSUE #496: [Layer dialog] No fields should be required in question if nothing is filled in
Otherwise we can't add layers without forms

### PR DESCRIPTION
**Pull request by parulraheja98**
Closes  #494 , #495, #496

### CODE REVIEW

**Review by gino-m — CHANGES_REQUESTED** [review]
It looks like you're disabling required validation altogether. How does the question field get validated once the user sets other attributes in the field/question (e.g. adds options)?

**Comment by gino-m** [comment]
Please be sure to mark as "Ready for review" and re-request review once ready. 💯

**Comment by gino-m** [comment]
Hi @parulraheja98 how's this PR coming along? Please let me know if you have any questions!

**Comment by parulraheja98** [comment]
Hello @gino-m , should be done very soon :)

**Comment by parulraheja98** [comment]
@gino-m , Ready for re-review

**Comment by parulraheja98** [comment]
Closing this PR and addressing this in new PR.

**Pull request closed without merging**
