### PR TITLE
Update firestore-tools and firestore-functions

### LINKED ISSUE #1696: [Code health] Update `firestore-tools` and `firestore-functions` for local emulation
I'm working end-to-end testing of the platform and app, which requires running the local emulation. I ran into issues with the older version of the `firebase-tools`, e.g.:

https://github.com/firebase/firebase-tools-ui/issues/939

Updating to version `13.1.0` did the trick for me. I also received a warning about `firebase-functions`, would be good to update that one too!

### PR DESCRIPTION
**Pull request by sufyanAbbasi**
Fixes #1696

Updates the `firestore-tools` and `firestore-functions` to the latest versions to make the local emulator work, useful for end-to-end testing.

### CODE REVIEW

**Review by gino-m — DISMISSED** [review]
Thanks, @sufyanAbbasi !

**Comment by gino-m** [comment]
Build is currently failing with:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: @angular/fire@7.[5](https://github.com/google/ground-platform/actions/runs/8532407822/job/23373502391?pr=1697#step:5:6).0
npm ERR! Found: firebase-tools@13.1.0
npm ERR! node_modules/firebase-tools
npm ERR!   dev firebase-tools@"13.1.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peerOptional firebase-tools@"^9.9.0 || ^10.0.0 || ^11.0.0" from @angular/fire@7.5.0
npm ERR! node_modules/@angular/fire
npm ERR!   @angular/fire@"^7.5.0" from the root project
npm ERR!   peer @angular/fire@"^[6](https://github.com/google/ground-platform/actions/runs/8532407822/job/23373502391?pr=1697#step:5:7).0.0 || ^[7](https://github.com/google/ground-platform/actions/runs/8532407822/job/23373502391?pr=1697#step:5:8).0.0" from firebaseui-angular@6.1.3
npm ERR!   node_modules/firebaseui-angular
npm ERR!     firebaseui-angular@"^6.1.2" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: firebase-tools@11.30.0
npm ERR! node_modules/firebase-tools
npm ERR!   peerOptional firebase-tools@"^[9](https://github.com/google/ground-platform/actions/runs/8532407822/job/23373502391?pr=1697#step:5:10).9.0 || ^10.0.0 || ^11.0.0" from @angular/fire@7.5.0
npm ERR!   node_modules/@angular/fire
npm ERR!     @angular/fire@"^7.5.0" from the root project
npm ERR!     peer @angular/fire@"^6.0.0 || ^7.0.0" from firebaseui-angular@6.1.3
npm ERR!     node_modules/firebaseui-angular
npm ERR!       firebaseui-angular@"^6.1.2" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/runner/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/[20](https://github.com/google/ground-platform/actions/runs/8532407822/job/23373502391?pr=1697#step:5:21)24-04-03T02_34_21_464Z-debug-0.log
Error: Process completed with exit code 1.
```

**Comment by sufyanAbbasi** [comment]
Fixed by changing to `npm install --legacy-peer-deps` in the Github Action test runner.

**Comment by rfontanarosa** [comment]
see https://github.com/google/ground-platform/pull/1772

**Pull request closed without merging**
