### PR TITLE
[Code health] Improvements to FormFieldEditorComponent 

### PR DESCRIPTION
**Pull request by parulraheja98**
Based on #442.

### CODE REVIEW

**Review by gino-m — APPROVED** [review]
This is so much clearer, I can even now understand each change in isolation without scanning the whole file. Thanks for the edits!

**Review by gino-m — CHANGES_REQUESTED** [review]
@parulraheja98 Tests are finally passing again after my last fix. Could you please resolve conflicts so we can merge? Thank you! 🙏

**Comment by parulraheja98** [comment]
Done @gino-m

**Comment by gino-m** [comment]
> Done @gino-m

Sorry I missed this! Please be sure to re-request review so I don't miss it!

**Review by gino-m — APPROVED** [review]
Nice work, as mentioned this is a great improvement. 💯 !

**Pull request merged**
