### PR TITLE
[Code health] Rename router-service to navigation-service

### LINKED ISSUE #427: [Code health] Rename "RouterService" to "NavigationService"
The service is responsible for navigating around the app, not for routing to different components.

### PR DESCRIPTION
**Pull request by Mvrs**
Fixes #427. Component names are now explicit and conventional around the application.

### CODE REVIEW

**Comment by Mvrs** [comment]
How to pass the trigger check? 👨🏿‍💻

**Comment by gino-m** [comment]
> How to pass the trigger check? 👨🏿‍💻

The build and test process seems to be a little flaky - looking into this now.

**Comment by gino-m** [comment]
@Mvrs Please `git pull upstream master` and resolve merge conflicts and I'll merge this ASAP!

**Comment by Mvrs** [comment]
> @Mvrs Please `git pull upstream master` and resolve merge conflicts and I'll merge this ASAP!

getting on that asap! My bad for the delay

**Review by gino-m — CHANGES_REQUESTED** [review]
Sorry for the delay! Some lint errors were reported:

```
/workspace/web-ng/src/app/components/main-page/main-page.component.ts
  92:32  error  'RouterService' is not defined  no-undef
```

Could you PTAL?

**Comment by Mvrs** [comment]
> Sorry for the delay! Some lint errors were reported:
> 
> ```
> /workspace/web-ng/src/app/components/main-page/main-page.component.ts
>   92:32  error  'RouterService' is not defined  no-undef
> ```
> 
> Could you PTAL?

Sure! No problem. And sorry for my delay. I'm still working on the other PR's and life has too busy the past three weeks. I'm looking forward to submitting my PR's within the following week ✊🏿.

**Comment by gino-m** [comment]
> > Sorry for the delay! Some lint errors were reported:
> > ```
> > /workspace/web-ng/src/app/components/main-page/main-page.component.ts
> >   92:32  error  'RouterService' is not defined  no-undef
> > ```
> > 
> > 
> > Could you PTAL?
> 
> Sure! No problem. And sorry for my delay. I'm still working on the other PR's and life has too busy the past three weeks. I'm looking forward to submitting my PR's within the following week ✊🏿.

No worries, same happened here! I'm planning to put more time into Ground this week. Excited to get your change merged!

**Review by gino-m — CHANGES_REQUESTED** [review]
@Mvrs so sorry there are new merge conflicts! If you resolve those I'll approve and merge ASAP!

**Review by gino-m — APPROVED** [review]
LGTM, thanks for this! 🥳

**Pull request merged**
