### PR TITLE
Add support for multiple choice tasks in submission detail view

### LINKED ISSUE #1278: [Feature] Add support for multiple choice tasks for submission detail panel

### PR DESCRIPTION
**Pull request by amysorto**
Fixes #1278

Note: There isn't a way to distinguish from the response data between "select one" vs. "select many" multiple choice questions right now. That is why the "select one" will also show a checkbox. Unselected options are not shown.

image

### CODE REVIEW

**Comment by gino-m** [comment]
Yes! Can we update the alignments and padding, or do that in a separate PR?

**Comment by gino-m** [comment]
@amysorto Gentle ping!

**Comment by gino-m** [comment]
Please also only show selected options (as discussed), not all options.

**Comment by amysorto** [comment]
> Yes! Can we update the alignments and padding, or do that in a separate PR?

Fixing the styling is the last part of #1132, so we can do this in a separate PR

**Review by gino-m — APPROVED** [review]
LGTM!

**Pull request merged**
