### PR TITLE
Updated drawing-tools File DOM text reinterpreted as HTML

### PR DESCRIPTION
**Pull request by Shivam7-1**
By using innerText, it will avoid the risk of HTML injection, as these properties automatically escape any HTML special characters in the provided text. This helps prevent cross-site scripting (XSS) vulnerabilities by treating the input as plain text rather than interpreted HTML. Always be cautious when dealing with user input or dynamic content to prevent security risks.

### CODE REVIEW

**Comment by Shivam7-1** [comment]
Hi @gino-m Could You Please Review Above PR
Thanks

**Comment by gino-m** [comment]
Tests fail with:
```
Error: Error: src/app/pages/main-page-container/main-page/drawing-tools/drawing-tools.component.spec.ts:328:23 - error TS2339: Property 'innerText' does not exist on type 'Element'.
```

**Comment by Shivam7-1** [comment]
Hi @gino-m Thanks For Reviewing 
I had check with above error it won't be able recognise innertext because of HTMLElement is not Declared 
Hence I had Added Those Change No Error will Occurs over here

Thanks

**Comment by Shivam7-1** [comment]
Hi @gino-m 
Is there any Changes are Required?

**Review by gino-m — APPROVED** [review]
LGTM!

**Comment by Shivam7-1** [comment]
Hi @gino-m Thanks For Reviewing
Above PR was approved recently, and I wanted to check in to see if there's anything else needed from my side to proceed with the merge.

Thanks

**Comment by NeilFraser** [comment]
@gino-m This test code is odd.  It apparently takes an HTML `IMG` tag and checks that `.innerHTML` (or now `.innerText`) contains a job name.  But HTML image tags don't contain either text or HTML.  Does this code even run?

**Comment by gino-m** [comment]
@NeilFraser Indeed it does. `job1Item` and `job12tem` are the `DIV`s surrounding the `IMG` elements, not the `IMG` elements themselves. Thanks for keeping an eye out, though. Grateful for your input elsewhere on the codebase if/when you have the cycles.

**Pull request merged**
