### PR TITLE
Cleanup of layer dialog css

### PR DESCRIPTION
**Pull request by parulraheja98**

### CODE REVIEW

**Review by gino-m — CHANGES_REQUESTED** [review]
Nice work! Could you provide a screen shot of the result?

**Comment by parulraheja98** [comment]
image

**Review by gino-m — APPROVED** [review]
LGTM.. 🚢 !

**Comment by shobhitagarwal1612** [comment]
@gino-m We can add a github template for PRs like we have one for the android repository with all relevant questions.

**Comment by gino-m** [comment]
> @gino-m We can add a github template for PRs like we have one for the android repository with all relevant questions.

Good idea.. for some reason I thought we had one already. I'll add one!

**Pull request merged**
