### PR TITLE
Sort imports in web/ via eslint

### LINKED ISSUE #1024: [Code health] Sort imports and enforce via eslint
For example:
https://medium.com/weekly-webtips/how-to-sort-imports-like-a-pro-in-typescript-4ee8afd7258a

### PR DESCRIPTION
**Pull request by semla**
I just followed the instructions, but afaict it works - tried running `ng lint --fix` a few times

Fixes #1024

### CODE REVIEW

**Comment by gino-m** [comment]
Did you `cd web` before running lint fix? When I run locally I see 180 files updated.

**Comment by semla** [comment]
Yes, many errors and warnings at first but after a few times it got down to 3 or 4.
afaict it works as intended?

**Comment by gino-m** [comment]
I don't see the reformatted files in this PR, which probably why tests are failing (see above).

**Comment by semla** [comment]
Ah, thought it was best to leave them out - but I can push a new commit.
After the third `ng lint --fix` this remains though:
```
$ ng lint --fix
Linting "web"...
ground-platform/web/e2e/src/app.e2e-spec.ts
  18:23  error  Unable to resolve path to module 'app.po'  import/no-unresolved
ground-platform/web/src/app/pages/create-survey/create-survey.component.spec.ts
  160:12  warning  Caution: `Immutable` also has a named export `List`. Check if you meant to write `import {List} from 'immutable'` instead  import/no-named-as-default-member
ground-platform/web/src/environments/environment.dev.ts
  17:30  error  Unable to resolve path to module 'environments/.firebase-config'  import/no-unresolved
ground-platform/web/src/environments/environment.prod.ts
  17:30  error  Unable to resolve path to module 'environments/.firebase-config'  import/no-unresolved
✖ 4 problems (3 errors, 1 warning)
Lint warnings found in the listed files.
Lint errors found in the listed files.

```

**Comment by gino-m** [comment]
> Ah, thought it was best to leave them out - but I can push a new commit. After the third `ng lint --fix` this remains though:
> 
> ```
> $ ng lint --fix
> Linting "web"...
> ground-platform/web/e2e/src/app.e2e-spec.ts
>   18:23  error  Unable to resolve path to module 'app.po'  import/no-unresolved
> ground-platform/web/src/app/pages/create-survey/create-survey.component.spec.ts
>   160:12  warning  Caution: `Immutable` also has a named export `List`. Check if you meant to write `import {List} from 'immutable'` instead  import/no-named-as-default-member
> ground-platform/web/src/environments/environment.dev.ts
>   17:30  error  Unable to resolve path to module 'environments/.firebase-config'  import/no-unresolved
> ground-platform/web/src/environments/environment.prod.ts
>   17:30  error  Unable to resolve path to module 'environments/.firebase-config'  import/no-unresolved
> ✖ 4 problems (3 errors, 1 warning)
> Lint warnings found in the listed files.
> Lint errors found in the listed files.
> ```

If you change the lint rules but don't update the files then the lint checks on existing files will fail.

Regarding the missing file, you can add the following placeholder to resolve that error:

```ts
export const firebaseConfig = {
  apiKey: '',
  authDomain: '',
  databaseURL: '',
  projectId: '',
  storageBucket: ',
  messagingSenderId: '',
  appId: '',
};
```

**Comment by gino-m** [comment]
> Delete the whole e2e directory? That's whats failing now. Protractor not used anyway?

That makes sense. Also please be sure to remove the `e2e` script in `web/package.json`. Thanks!

**Review by gino-m — DISMISSED** [review]
LGTM! Thanks for this cleanup!

**Comment by gino-m** [comment]
@semla Could you please resolve conflicts? I believe the easiest way would be to "Accept theirs" for all conflicting files and rerunning `npm run lint:fix`. Thanks again!

**Review by gino-m — APPROVED** [review]
✅ 🏆  LGTM!

**Pull request merged**
