### PR TITLE
Added Data Sharing Content section to edit survey details page

### PR DESCRIPTION
**Pull request by nwkotto**

### CODE REVIEW

**Comment by nwkotto** [comment]
Screenshot 2024-08-16 at 5 32 41 PM
Screenshot 2024-08-16 at 5 33 26 PM

**Comment by amegantz** [comment]
Content for all survey types:
image
Private
Data will only be shared with survey organizers, who may not share and use collected data publicly

Public
Survey organizers may share and use data publicly under [the CC0 license](https://creativecommons.org/public-domain/cc0/)

Custom
Provide a custom agreement the data collector must accept before collecting data

**Comment by gino-m** [comment]
> Content for all survey types: image Private Data will only be shared with survey organizers, who may not share and use collected data publicly
> 
> Public Survey organizers may share and use data publicly under [the CC0 license](https://creativecommons.org/public-domain/cc0/)
> 
> Custom Provide a custom agreement the data collector must accept before collecting data

@nwkotto FYI

**Comment by nwkotto** [comment]
Thanks! Just updated the PR with that link

**Comment by nwkotto** [comment]
image
image

**Review by gino-m — APPROVED** [review]
LGTM, modulo failing tests.

**Review by amysorto — APPROVED** [review]

**Pull request merged**
